-- MySQL Script generated by MySQL Workbench
-- Wed May  4 18:15:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pokemonDB
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Types` (
  `typeID` INT NOT NULL AUTO_INCREMENT,
  `typeName` VARCHAR(20) NOT NULL,
  `invulnerableAgainst` INT NULL,
  PRIMARY KEY (`typeID`),
  UNIQUE INDEX `typeID_UNIQUE` (`typeID` ASC) VISIBLE,
  UNIQUE INDEX `typeName_UNIQUE` (`typeName` ASC) VISIBLE,
  INDEX `invulnerableAgainst_idx` (`invulnerableAgainst` ASC) VISIBLE,
  CONSTRAINT `invulnerableAgainst`
    FOREIGN KEY (`invulnerableAgainst`)
    REFERENCES `Types` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Generations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Generations` (
  `genID` INT NOT NULL AUTO_INCREMENT,
  `releaseDate` DATETIME NOT NULL,
  `region` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`genID`),
  UNIQUE INDEX `generationID_UNIQUE` (`genID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokemon` (
  `pokemonID` INT NOT NULL AUTO_INCREMENT,
  `pokemonName` VARCHAR(20) NOT NULL,
  `typeID1` INT NOT NULL,
  `typeID2` INT NULL,
  `genID` INT NULL,
  `preEvolution` VARCHAR(20) NULL,
  `postEvolution` VARCHAR(45) NULL,
  PRIMARY KEY (`pokemonID`),
  UNIQUE INDEX `pokemonID_UNIQUE` (`pokemonID` ASC) VISIBLE,
  INDEX `fk_Pokemon_Types1_idx` (`typeID1` ASC) VISIBLE,
  INDEX `fk_Pokemon_Types2_idx` (`typeID2` ASC) VISIBLE,
  INDEX `fk_Pokemon_Generations1_idx` (`genID` ASC) VISIBLE,
  CONSTRAINT `fk_Pokemon_Types1`
    FOREIGN KEY (`typeID1`)
    REFERENCES `Types` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemon_Types2`
    FOREIGN KEY (`typeID2`)
    REFERENCES `Types` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemon_Generations1`
    FOREIGN KEY (`genID`)
    REFERENCES `Generations` (`genID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Attacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Attacks` (
  `attackID` INT NOT NULL AUTO_INCREMENT,
  `attackName` VARCHAR(45) NOT NULL,
  `typeID` INT NOT NULL,
  `power` INT NULL,
  `accuracy` INT NULL,
  `PP` INT NOT NULL,
  PRIMARY KEY (`attackID`),
  UNIQUE INDEX `attackID_UNIQUE` (`attackID` ASC) VISIBLE,
  INDEX `fk_Attacks_Types1_idx` (`typeID` ASC) VISIBLE,
  UNIQUE INDEX `attackName_UNIQUE` (`attackName` ASC) VISIBLE,
  CONSTRAINT `fk_Attacks_Types1`
    FOREIGN KEY (`typeID`)
    REFERENCES `Types` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pokemon_Attacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pokemon_Attacks` (
  `pokemon_attackID` INT NOT NULL AUTO_INCREMENT,
  `pokemonID` INT NOT NULL,
  `attackID` INT NOT NULL,
  INDEX `fk_Pokemon_has_Attacks_Pokemon1_idx` (`pokemonID` ASC) VISIBLE,
  INDEX `fk_Pokemon_has_Attacks_Attacks1_idx` (`attackID` ASC) VISIBLE,
  PRIMARY KEY (`pokemon_attackID`, `pokemonID`, `attackID`),
  CONSTRAINT `pokemonID`
    FOREIGN KEY (`pokemonID`)
    REFERENCES `Pokemon` (`pokemonID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `attackID`
    FOREIGN KEY (`attackID`)
    REFERENCES `Attacks` (`attackID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- ----------------------------------------------------
-- Insert data into `Types`
-- ----------------------------------------------------
INSERT INTO `Types` (`typeName`, `invulnerableAgainst`) VALUES
("Grass", null),
("Fire", null),
("Ground", null),
("Flying", 3),
("Poison", null);


-- ----------------------------------------------------
-- Insert data into `Generations`
-- ----------------------------------------------------
INSERT INTO `Generations` (`releaseDate`, `region`) VALUES
("1998-09-28", "Kanto"),
("2000-08-15", "Johto"),
("2003-03-19", "Hoenn");

-- ----------------------------------------------------
-- Insert data into `Pokemon`
-- ----------------------------------------------------
INSERT INTO `Pokemon` (`pokemonName`, `typeID1`, `typeID2`, `genID`, `preEvolution`, `postEvolution`) VALUES
('Bulbasaur', (SELECT typeID FROM Types WHERE typeName = 'Grass'), (SELECT typeID FROM Types WHERE typeName = 'Poison'), 1, null, 2),
('Ivysaur', (SELECT typeID FROM Types WHERE typeName = 'Grass'), (SELECT typeID FROM Types WHERE typeName = 'Poison'), 1, 1, 3),
('Venusaur', (SELECT typeID FROM Types WHERE typeName = 'Grass'), (SELECT typeID FROM Types WHERE typeName = 'Poison'), 1, 2, null),
('Charmander', (SELECT typeID FROM Types WHERE typeName = 'Fire'), null, 1, null, 4);

-- ----------------------------------------------------
-- Insert data into `Attacks`
-- ----------------------------------------------------
INSERT INTO `Attacks` (`attackName`, `typeID`, `power`, `accuracy`, `PP`) VALUES
('Ember', (SELECT typeID FROM Types WHERE typeName = 'Fire'), 40, 100, 25),
('Leech Seed', (SELECT typeID FROM Types WHERE typeName = 'Grass'), null, 90, 10),
('Vine Whip', (SELECT typeID FROM Types WHERE typeName = 'Grass'), 35, 100, 25);


-- ----------------------------------------------------
-- Insert data into `Pokemon_Attacks`
-- ----------------------------------------------------
INSERT INTO `Pokemon_Attacks` (`pokemonID`, `attackID`) VALUES
((SELECT pokemonID FROM Pokemon WHERE pokemonName = "Bulbasaur"),
  (SELECT attackID FROM Attacks WHERE attackName = "Vine Whip")),
((SELECT pokemonID FROM Pokemon WHERE pokemonName = "Ivysaur"),
  (SELECT attackID FROM Attacks WHERE attackName = "Vine Whip")),
((SELECT pokemonID FROM Pokemon WHERE pokemonName = "Ivysaur"),
  (SELECT attackID FROM Attacks WHERE attackName = "Leech Seed")),
((SELECT pokemonID FROM Pokemon WHERE pokemonName = "Charmander"),
  (SELECT attackID FROM Attacks WHERE attackName = "Ember"));
